### ISSUE TITLE
Event tracking gives undefined category and name

### ISSUE THREAD

**Issue by BastianHofmann** [angulartics/angulartics-piwik#10]
I want to track an event like this:
`$analytics.eventTrack('login', { category: 'auth', label: 'success' });`

When this code is run I get a new event in my piwik installation as expected, but the category is set to `undefined` and the name says `Event Name not defined` (Action is set to `auth`).
I want category = auth, action = login, name = success.

Am I missing something? I took the code from http://angulartics.github.io/#/event-tracking "Using the API".

**Comment by WuglyakBolgoink** [comment]
Hi @BastianHofmann any news?

**Comment by BastianHofmann** [comment]
@WuglyakBolgoink Currently working with the same code. Not sure what I changed, sorry.

**Comment by WuglyakBolgoink** [comment]
@BastianHofmann  How do u do EventTracking? on my dev-Server I can't see any events on piwik, but plugin response send 200-OK back.

```js
sendEventWithParams: function(category, action, label, value, params) {
    // $window.ga('send', 'event', category, action, label, value); // old

    $analytics.eventTrack(category, {
        category: category,
        label: label,
        action: action,
        value: value,
        params: params
    });
}
```
