### ISSUE TITLE
How to trackPageView after setting a custom variable ?

### ISSUE THREAD

**Issue by iliassk** [angulartics/angulartics-piwik#13]
I'm trying to set a custom variable in my controller, but I don't know how I can call trackPageView to record the request ?
If I'm refering to Piwik documentation :

> To persist the change in the Piwik server, you must call the function before the call to trackPageView();

https://developer.piwik.org/2.x/guides/tracking-javascript-guide#custom-variable-for-page-views

Thanks.

**Comment by inolasco** [comment]
That's pretty much handled automatically by the module. You only need to add a call like this in your controller:

```
$analytics.setCustomVariable(1, 'The var name', 'The var value', 'visit');
```

And angulartics should take care of the details.

**Comment by iliassk** [comment]
It's automatically handled for event and click actions, but what about visit actions ?

For example, I want to track a user **visit** when the user is anonymous and when logged in. Is it possible to "refresh" the custom variable for the visit ? (I can't use visitor ID) 

```js
$analytics.setCustomVariable(5, "user", "anon", "page");
$rootScope.$on("LoginSuccess", function() {
       var connectedUser = AuthService.getUser();
       $analytics.setCustomVariable(5, "user", connectedUser, "page");
 
});
```
