### ISSUE TITLE
Missing TrackLink api method

### ISSUE THREAD

**Issue by patfrat** [angulartics/angulartics-piwik#3]
Hello,

It will be great to add trackLink support too.

``` javascript
$analyticsProvider.api.trackLink = function(url, linkType) {
  if ($window._paq) {
    $window._paq.push(['trackLink', url, linkType]);
  }
};
```

**Comment by inolasco** [comment]
Looks good. Could you please make a pull request with this? If not I can add it later. Also, `linkType` should maybe default to `'link'`.

**Comment by patfrat** [comment]
Thanks for the merge.
Could you tag your project with a new minor version 1.0.3 with this change ?
I use bower to install it with this tag : 
    "angulartics-piwik": "1.0.x"
And it download 1.0.2 version without trackLink method.

**Comment by inolasco** [comment]
Sorry for the delay, I just merged your latest pull request, and updated both bower and npm. Thanks!
